services:
  db:
    image: postgres:15
    container_name: swu_postgres
    restart: always
    environment:
      POSTGRES_DB: swu_api_cards
      POSTGRES_USER: swu_user
      POSTGRES_PASSWORD: SuperSecret!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: swu_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: toto@toto.com
      PGADMIN_DEFAULT_PASSWORD: toto
    ports:
      - "5050:80"  

volumes:
  postgres_data:
    driver: local

